### ISSUE TITLE
Running bizarro CMS

### ISSUE THREAD

**Issue by MrMaksimize** [codeforamerica/bizarro-cms#12]
Hey y'all,

I barely know anything about python, so forgive me for dumb questions.

So I tried to run bizarro CMS, however when I attempted to log in, because I was running from localhost mozilla persona wouldn't let me in.

Do you have another strategy in right now for authenticating locally?

Thanks!

**Comment by phae** [comment]
I'm cleaning up the issues for our next piece of work on this, so I'm going to close this now @MrMaksimize. If you get back into this and want to play with stuff, give us a shout!
